### ISSUE TITLE
Tool does not work right in LongitudinalPETCT

### ISSUE THREAD

**Issue by pieper** [chribaue/PETTumorSegmentation#10]
When this effect is used in the embedded EditorWidget of [LongitudinalPETCT](https://github.com/QIICR/LongitudinalPETCT) the undo/redo functionality is not working correctly.

One issue that the code [accesses the Editor module widget](https://github.com/QIICR/PETTumorSegmentation/blob/master/PETTumorSegmentationEffect/PETTumorSegmentationEffect.py#L204-L233) which may not exist if the Editor module has not been entered, and in any case the variable would not be associated with the buttons in the embedded widget.

Since the effect tool is passed in the Editor's instance of the UndoRedo class it should be possible to implement the save and restore state functionality without accessing the widget.

**Comment by pieper** [comment]
It may make the most sense to rework this entirely as a Segmentation Editor effect.

**Comment by chribaue** [comment]
> It may make the most sense to rework this entirely as a Segmentation Editor effect.

The good news: We have already reworked the tool entirely as a Segment Editor effect and it can already be use e.g. in the Quantiative Reporting module.

The bad news: This doesn't fix the issue when using the "classic" Editor Effect in the LongitudinalPETCT module.

> Since the effect tool is passed in the Editor's instance of the UndoRedo class it should be possible to implement the save and restore state functionality without accessing the widget.

The Editor Lib's UndoRedo class has a stateChangedCallback which is used by the EditBox. But the class doesn't allow me registering additional callbacks. So I don't see any good way to monitor when an undo or redo occurs. If you have suggestions, please me know.

**Comment by pieper** [comment]
We could rework the undo/redo mechanism of the EditorLib code, but is it still needed?  Are we ready to switch completely to the SegmentEditor?

**Comment by chribaue** [comment]
I think most people from now on will use the SegmentEditor based Effect and the new Segmentation framework in general, instead of the older Labelmap based Editor. I just don't want to remove the old EditorLib EditorEffect yet, since it's also in use in our PET IndiC module (with working undo/redo), but we're transitioning to using QuantitativeReporting.

Ideally, the Longitudinal Analysis would switch to using the new SegmentEditor framework. But that would require considerably more work than reworking the EditorLib's undo/redo mechanism to allow registering additional callbacks.

**Comment by fedorov** [comment]
@chribaue what is missing in SegmentEditor that is preventing you from implementing "working undo/redo"?

**Comment by chribaue** [comment]
@fedorov As mentioned above, the SegmentEditorEffect has working undo/redo and the EditorEffect has undo/redo that works properly when used in the Editor-Module and in the PET-IndiC module.
But, the EditorEffect's undo/redo does not work properly when used in the LongitudinalPETCT module. The reason is because the Editor's undo/redo functionality in Slicer was not designed in a way that allows developers to extend the undo/redo functionality. Fixing this issue would require changes to Slicer's EditorLib, which is going to be replaced by the newer SegmentEditor.

**Comment by chribaue** [comment]
issue fixed in https://github.com/QIICR/PETTumorSegmentation/commit/82b33b5d0365e6cbcbab42af64dde2493f8ac3ed
